### PR TITLE
Add tea meme option

### PR DESCRIPTION
**Pull request by sheixt**
Thought this may be of interest... I've extended the slack bot to use Google's Custom Search API to retrieve an image and append it to the slack bot's message. We use it to grab a tea meme!

### CODE REVIEW

**Comment by mikestreety** [comment]
Excellent, thanks!

Have you got a screenshot of it in action?

**Comment by mikestreety** [comment]
(p.s. glad to see someone is using it :smile: )

**Comment by sheixt** [comment]
Sure! Here you go:
hb1om

Thanks for doing the the main heavy lifting!

**Comment by sheixt** [comment]
I would note there's an implied understanding of creating a Google Custom Search and enabling that API before you are about to generate the API key and ID... but google's got that documented.

**Comment by mikestreety** [comment]
Cool thanks, might tweak and add some conditional statements in there. :) Mind dropping a link to the docs so I can make sure I've got the right one?

You also reference a `$show_meme` var which I can't see where that gets set?

**Comment by mikestreety** [comment]
Hi @sheixt - any chance I could get that documentation link? Thanks :)

**Comment by mikestreety** [comment]
Rather than use google search, I might use a giphy search fior "tea and coffee" (as that doesn't need an API)

https://giphy.com/search/tea-and-coffee

**Pull request closed without merging**
